### ISSUE TITLE
It doesn't show updates when `--network-interval-seconds` has a big number

### ISSUE THREAD

**Issue by c02y** [coffebar/waybar-module-pacman-updates#11]
**Describe the bug**

**To Reproduce**
```
  "custom/updates": {
    "format": " {icon} {}",
    "return-type": "json",
    "format-icons": {
      "has-updates": "",
      "updated": ""
    },
    "exec-if": "which waybar-module-pacman-updates",
    "exec": "waybar-module-pacman-updates  --interval-seconds 5 --network-interval-seconds 86400"
  },
```
When I change `--network-interval-seconds 86400` to `--network-interval-seconds 300` like the number in the README, I can see there is a notifcication icon and number of available updates in my waybar, but when I use `86400` which is one day, I see nothing in the waybar

Is it normal?

**Expected behavior**

**Additional context**

**Comment by coffebar** [comment]
Maximum value changed 
65_535 -> 4_294_967_295
