### ISSUE TITLE
Hide module if no updates

### ISSUE THREAD

**Issue by beucismis** [coffebar/waybar-module-pacman-updates#12]
Hi, I'm try...

```
waybar-module-pacman-updates | jq .text
```

If outpus is "0", hide. With waybar `exec-if` state. But not working.

**Comment by coffebar** [comment]
maybe you want just --no-zero-output option and set no icon when no updates?

**Comment by beucismis** [comment]
Yep.

**Comment by coffebar** [comment]
try this:
```json
    "custom/updates": {
        "format": "{} {icon}",
        "return-type": "json",
        "format-icons": {
            "has-updates": "󱍷",
            "updated": ""
        },
        "exec-if": "which waybar-module-pacman-updates",
        "exec": "waybar-module-pacman-updates --no-zero-output"
    }

```

**Comment by beucismis** [comment]
Not exactly what I wanted...

**Comment by michaeljaeger95** [comment]
I'm sorry for necrobumping, but would you consider adding this tip to the readme? I think this is an issue several people might have (I'm eveidently at least the second) and not everyone will figure out to look in closed issues for this.

**Comment by coffebar** [comment]
done

**Comment by Insprill** [comment]
Just a note here for others who find this issue: if you want the element to be hidden completely when there are no updates (useful if it has a background), remove the space between `{}` and `{icon}`, then add the space to the has-updates icon.
```json
...
"format": "{}{icon}",
"format-icons": {
    "has-updates": " 󱍷",
    "updated": ""
}
...
```
