### ISSUE TITLE
Cannot make icon appear on the left hand side

### ISSUE THREAD

**Issue by GoGoGadgetGitHub** [coffebar/waybar-module-pacman-updates#14]
**Describe the bug**
When I try to swap `{}` and `{icon}` I get an error

`custom/updates: cannot switch from manual to automatic argument indexing`

**To Reproduce**
1. Add module to waybar config
2. Try to swap `{}` and `{icon}` to make the update icon appear on the left hand side

**Additional context**
I am using a span element on the text as-well but I tested this with the icon right text left order and it worked fine.

```
"custom/updates": {
  "format": "{icon} <span color=\"#c2c2c2\">{}</span>",
  "return-type": "json",
  "format-icons": {
	  "has-updates": "󱍷",
	  "updated": "󰂪"
  },
  "exec-if": "which waybar-module-pacman-updates",
  "exec": "waybar-module-pacman-updates --interval-seconds 5 --network-interval-seconds 300"
}
```

**Comment by coffebar** [comment]
Please try this https://github.com/Alexays/Waybar/issues/3623#issuecomment-2357239438

**Comment by GoGoGadgetGitHub** [comment]
That does stop the error, but the icon doesn't show

![image](https://github.com/user-attachments/assets/87d4d99d-1a78-455c-8602-84147b38ae53)

**Comment by coffebar** [comment]
```        "format": "{icon} {0}", ```
works for me

_before_
![screenshot-2](https://github.com/user-attachments/assets/c4299093-ea1b-472a-92e0-505f1302d88b)

_after_ 
![screenshot-1](https://github.com/user-attachments/assets/92005f05-d8d5-4104-85a4-33275cd62939)

**Comment by GoGoGadgetGitHub** [comment]
oh that seemed to do the trick, i appreciate the help, ig i should have read that tread a bit more.
