### ISSUE TITLE
Add Timer

### ISSUE THREAD

**Issue by gutohertzog** [coffebar/waybar-module-pacman-updates#5]
Awesome repo.

I think would be awesome if was possible to set an interval for checking for updates.
As far I could see, it checks for update every 10 or so seconds.

For example, it could check every 6 hours like :
`waybar-module-pacman-updates 21600`

**Comment by coffebar** [comment]
It makes sense to name an argument, for example 

``` --interval-seconds 21600 ```

Do you want to do PR?

**Comment by gutohertzog** [comment]
I would love, but I have no knowledge in Rust, sorry =[

Only SQL (for work), Python (to teach and solve problems from work) and a bit of C++ for fun.

**Comment by gutohertzog** [comment]
Thanks for this new feature S2
