### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by alexlnkp** [coffebar/waybar-module-pacman-updates#6]
**Is your feature request related to a problem? Please describe.**
I would like to disable notifications for when an update is available. A number next to a download icon is enough for me.

**Describe the solution you'd like**
Make the notification a flag, either enabled or disabled by default.

**Describe alternatives you've considered**
I've looked into `checkupdates`, but i believe that this module has a lot of potential and is going to be much of a better fit for my needs.

**Comment by coffebar** [comment]
Notifications are not going from this project. We don't have such feature

**Comment by alexlnkp** [comment]
Sorry... I've confused a project inspired by yours with another one...
Forgot to actually switch to your project once i discovered it...

Sorry for wasting your time
